### ISSUE TITLE
feature add: change the url shortener that twitter use to use the real link rather than their shortened url

### ISSUE THREAD

**Issue by duncanhealy** [lirantal/twiks#1]
I stop clicking on urls in tweets because of Twitters url shortener (t.co/..) 
Twitter could just leave the url alone (arguably protecting links from scraping malware etc)

however they leave the url in the title

This could be done by adding something similar to below 
```
document.querySelectorAll('[href*="https://t.co/"]').forEach(el=>{if(el.title){el.href=el.title}})
```
- [x] Is it something to add ?
- [ ] do twitters tos allow this?

**Comment by lirantal** [comment]
Good stuff!
