### ISSUE TITLE
change pause to :play_or_pause_button:

### ISSUE THREAD

**Issue by duncanhealy** [lirantal/twiks#4]
:pause_button: :arrow_forward: icons for pause rather than pause paused 

:play_or_pause_button: should be default

:pause_button: if the feed has been paused

:arrow_forward: if the feed has been unpaused

**Comment by lirantal** [comment]
I added it as follows:

![image](https://user-images.githubusercontent.com/316371/93665243-9839c400-fa7d-11ea-9890-8dd500f366b0.png)

and

![image](https://user-images.githubusercontent.com/316371/93665241-93751000-fa7d-11ea-89f7-561a4192bd92.png)


Should be available on the next update!
